### ISSUE TITLE
Sound Effects sometimes break

### ISSUE THREAD

**Issue by KeiferMonk** [ShiningForceRemade/SFR-Godot#9]
i.e when Tao casts Blaze there's no hit sound.

**Comment by feldc** [comment]
What happened was the cast sound and the battle encounter are both playing at the same time so the hit sound wasn't heard. I moved the hit sound effect to play when the enemey actor  begins the white flashing and shake animation.

If there's other sound effects that are missing or broken feel free to leave a comment (I'll re-open the issue and address the comments). 

Thanks @KeiferMonk for all the bug reports.
